name: Run mabl Tests

on:
  push:
    branches:
      - master

jobs:
  mabl-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install mabl CLI
        run: npm install -g @mablhq/mabl-cli

      - name: Run mabl Tests
        run: |
          mabl auth activate-key $MABL_API_KEY
          mabl tests run --from-plan-id qskFEzdq4CtODVQDqogwjQ-p
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
